bot:
  name: Newsstand Bot
  welcome_message: 'Welcome to the Newsstand Bot! 📰

    Get your favourite Indian newspapers delivered to Telegram every morning.

    Use /browse to explore titles, /subscribe to add papers, and /mystuff to manage
    subscriptions.

    '
storage:
  channel_id: ${STORAGE_CHANNEL_ID}
schedule:
  timezone: Asia/Kolkata
  first_check: 05:30
  retry_interval_minutes: 60
  stop_retrying: '12:00'
  max_retries: 6
titles:
- name: Mirror
  slug: mirror
  source_url: https://dailyepaper.in/ahmedabad-mirror-epaper-download-2026/
  language: English
  category: Newspaper
  scrape_website: dailyepaper_in
  
- name: Business Line
  slug: business-line
  source_url: https://www.careerswave.in/business-line-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Economic Times
  slug: economic-times
  source_url: https://www.careerswave.in/economic-times-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Hindustan Times
  slug: hindustan-times
  source_url: https://www.careerswave.in/hindustan-times-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: The Times of India
  slug: the-times-of-india
  source_url: https://www.careerswave.in/times-of-india-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: The Telegraph
  slug: the-telegraph
  source_url: https://www.careerswave.in/telegraph-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Business Standard
  slug: business-standard
  source_url: https://www.careerswave.in/business-standard-newspaper-in-pdf/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: First India
  slug: first-india
  source_url: https://www.careerswave.in/first-india-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Telangana Today
  slug: telangana-today
  source_url: https://www.careerswave.in/telangana-today-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Mumbai Mirror
  slug: mumbai-mirror
  source_url: https://www.careerswave.in/mumbai-mirror-epaper-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: The Financial Express
  slug: the-financial-express
  source_url: https://www.careerswave.in/the-financial-express-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Deccan Chronicle
  slug: deccan-chronicle
  source_url: https://www.careerswave.in/deccan-chronicle-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Live Mint
  slug: live-mint
  source_url: https://www.careerswave.in/mint-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: The Statesman
  slug: the-statesman
  source_url: https://www.careerswave.in/the-statesman-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: The Tribune
  slug: the-tribune
  source_url: https://www.careerswave.in/the-tribune-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: The Asian Age
  slug: the-asian-age
  source_url: https://www.careerswave.in/the-asian-age-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Hans India
  slug: hans-india
  source_url: https://www.careerswave.in/hans-india-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: The Greater Kashmir
  slug: the-greater-kashmir
  source_url: https://www.careerswave.in/greater-kashmir-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: The Pioneer
  slug: the-pioneer
  source_url: https://www.careerswave.in/the-pioneer-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Free Press Journal
  slug: free-press-journal
  source_url: https://www.careerswave.in/free-press-journal-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Oheraldo
  slug: oheraldo
  source_url: https://www.careerswave.in/o-heraldo-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Nagaland Post
  slug: nagaland-post
  source_url: https://www.careerswave.in/nagaland-post-epaper-pdf-down/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: State Times
  slug: state-times
  source_url: https://www.careerswave.in/state-times-epaper-pdf-free-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Assam Tribune
  slug: assam-tribune
  source_url: https://www.careerswave.in/assam-tribune-epaper-download-daily-after-0630-am/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Arunachal Times
  slug: arunachal-times
  source_url: https://www.careerswave.in/arunachal-times-epaper-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Kashmir Times
  slug: kashmir-times
  source_url: https://www.careerswave.in/kashmir-times-epaper-download/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Millennium Post
  slug: millennium-post
  source_url: https://www.careerswave.in/millennium-post-epaper-p2024-free-pdf/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Deccan Herald
  slug: deccan-herald
  source_url: https://www.careerswave.in/deccan-herald-epaper-p2024-free-pdf/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Lokmat Times
  slug: lokmat-times
  source_url: https://www.careerswave.in/lokmat-times-epaper-p2024-free-pdf/
  language: English
  category: Newspaper
  scrape_website: careerswave_in

- name: Amar ujala
  slug: amar-ujala
  source_url: https://www.careerswave.in/amar-ujala-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: आईनेक्स्ट लाइव
  slug: inext-live
  source_url: https://dailyepaper.in/inext-live-epaper-epaper-download-2026/
  language: Hindi
  category: Newspaper
  scrape_website: dailyepaper_in

- name: Lokmat
  slug: lokmat
  source_url: https://dailyepaper.in/lokmat-epaper-download-2026/
  language: Hindi
  category: Newspaper
  scrape_website: dailyepaper_in

- name: Nav Bharat
  slug: nav-bharat
  source_url: https://dailyepaper.in/navabharat-epaper-download-2026/
  language: Hindi
  category: Newspaper
  scrape_website: dailyepaper_in

- name: Dainik Jagran
  slug: dainik-jagran
  source_url: https://www.careerswave.in/dainik-jagran-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Hindustan
  slug: hindustan
  source_url: https://www.careerswave.in/hindustan-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: The Pioneer (Hindi)
  slug: the-pioneer-hindi
  source_url: https://www.careerswave.in/the-pioneer-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Prabhat Khabar
  slug: prabhat-khabar
  source_url: https://www.careerswave.in/prabhat-khabar-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Jansatta
  slug: jansatta
  source_url: https://www.careerswave.in/jansatta-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Navbharat Times
  slug: navbharat-times
  source_url: https://www.careerswave.in/navbharat-times-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Rajasthan Patrika
  slug: rajasthan-patrika
  source_url: https://www.careerswave.in/rajasthan-patrika-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Dainik Navajyoti
  slug: dainik-navajyoti
  source_url: https://www.careerswave.in/dainik-navajyoti-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Punjab Kesari
  slug: punjab-kesari
  source_url: https://www.careerswave.in/punjab-kesari-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Dainik Bhaskar
  slug: dainik-bhaskar
  source_url: https://www.careerswave.in/dainik-bhaskar-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Business Standard (Hindi)
  slug: business-standard-hindi
  source_url: https://www.careerswave.in/business-standard-newspaper-in-pdf/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Hari Bhoomi
  slug: hari-bhoomi
  source_url: https://www.careerswave.in/hari-bhoomi-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Samachar Jagat
  slug: samachar-jagat
  source_url: https://www.careerswave.in/samachar-jagat-epaper-p2024-free-pdf/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Rashtriya Sahara
  slug: rashtriya-sahara
  source_url: https://www.careerswave.in/rashtriya-sahara-epaper-pdf-free-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Nai Dunia
  slug: nai-dunia
  source_url: https://www.careerswave.in/nai-dunia-epaper-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Lokmat Samachar
  slug: lokmat-samachar
  source_url: https://www.careerswave.in/lokmat-samachar-epaper-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Lok Tej
  slug: lok-tej
  source_url: https://www.careerswave.in/lok-tej-epaper-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Divya Himachal
  slug: divya-himachal
  source_url: https://www.careerswave.in/divya-himachal-epaper-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Deshbandhu
  slug: deshbandhu
  source_url: https://www.careerswave.in/deshbandhu-newspaper-p2024-free-pdf/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in

- name: Uttam Hindu
  slug: uttam-hindu
  source_url: https://www.careerswave.in/uttam-hindu-epaper-download/
  language: Hindi
  category: Newspaper
  scrape_website: careerswave_in


